### ISSUE TITLE
Version published to npm registry is out of date and has a severe bug

### ISSUE THREAD

**Issue by aluanhaddad** [saintmac/angular-cache-buster#11]
The npm package is out of date. Specifically, it is missing commits d55f71e2b33df751bee487b3ad5e82622e8516e1 and d37a15be7b6dc08088653e6d0236583b15885979,
thus making it unsuitable for use in modern minification scenarios. We like this module, but our team has moved away from bower and this is a headache.

**Comment by feimosi** [comment]
:+1:

**Comment by reecefenwick** [comment]
How is this still not resolved...

**Comment by aluanhaddad** [comment]
@feimosi Thanks for the tip. We actually use jspm but that commit syntax should work there as well. @reecefenwick yeah, this needs to be resolved...

**Comment by erdog** [comment]
:+1:

**Comment by saintmac** [comment]
@aluanhaddad @feimosi @reecefenwick @erdog Sorry guys this has just been fixed
