### ISSUE TITLE
Let publish the latest version in npmregistry

### ISSUE THREAD

**Issue by jBouyoud** [saintmac/angular-cache-buster#14]
Hi,

Latest version is not published into npmregistry.
Could you please publish it.

Thanks.

**Comment by clintonmedbery** [comment]
Would be nice.

**Comment by saintmac** [comment]
@jBouyoud @clintonmedbery 
Thanks guys for pointing that out. 0.4.3 is now on NPM :-)

**Comment by clintonmedbery** [comment]
Thanks!
